- hosts: all
  gather_facts: no
  ignore_errors: true
  # Hack for Ubuntu 16
  pre_tasks:
    - name: Install python2
      raw: "command -v python || sudo apt-get -y install python-simplejson"
      changed_when: false
  tags:
    - prepare

- hosts: all
  gather_facts: yes
  roles:
    - { role: setup, tags: ['prepare'] }
    - { role: docker_install, become: true, tags: ['docker'] }

- hosts: all
  gather_facts: yes
  roles:
    - { role: docker_config, become: true, tags: ['docker_config'] }
