---
- include: ../update_cache/yum_update.yml

- when: upgrade|bool
  block:
    - name: YUM update
      yum: name=* state=latest
      register: updated

    - include: restart.yml
      when: updated.changed
