# Configuration options with defaults
docker_configure:
#  "api-cors-header":
#  "authorization-plugins":
#  bip:
#  bridge:
#  "cgroup-parent":
#  "cluster-store":
#  "cluster-store-opts":
#  "cluster-advertise":
  debug: true
#  "default-gateway":
#  "default-gateway-v6":
#  "default-runtime": runc
#  "default-ulimits":
#  "disable-legacy-registry": false
  dns:
    - 8.8.8.8
    - 8.8.4.4
#  "dns-opts":
#  "dns-search":
#  "exec-opts":
#  "exec-root":
#  "fixed-cidr":
#  "fixed-cidr-v6":
#  graph:
#  group:
#  hosts:
#  icc: false
#  "insecure-registries":
  ip: 0.0.0.0
#  iptables: false
#  ipv6: false
#  "ip-forward": false
#  "ip-masq": false
#  labels:
  "live-restore": true
#  "log-driver":
#  "log-level":
#  "log-opts":
  "max-concurrent-downloads": 3
  "max-concurrent-uploads": 5
#  mtu:
#  "oom-score-adjust": -500
#  pidfile:
#  "raw-logs": false
#  "registry-mirrors":
#  runtimes: {"runc": {"path": "runc"}, "custom": {"path": "/usr/local/bin/my-runc-replacement", "runtimeArgs": ["--debug"]}}
#  "selinux-enabled": false
  "storage-driver": "devicemapper"
#  "storage-opts":
#  swarm-default-advertise-addr:
#  tls: true
#  tlscacert:
#  tlscert:
#  tlskey:
#  tlsverify: true
#  "userland-proxy": false
#  "userns-remap":
