
- name: Create user
  user:
    name: "{{ host_username }}"
    shell: /bin/bash
    groups: "{{ user_groups|join(',') }}"
    append: yes

- name: Set authorized key took from url
  authorized_key:
    user: "{{ host_username }}"
    state: present
    key: "{{ item }}"
    exclusive: true
  with_items:
    - "{{ key_urls }}"

