
- name: Create user
  user:
    name: "{{ host_username }}"
    shell: /bin/bash
    groups: "{{ user_groups|join(',') }}"
    append: yes

- name: Clean up temporary authorized file
  copy:
    content: '# ANSIBLE GENERATED SSH KEYS FILE'
    dest: "/tmp/auth_keys"
    force: yes

- name: Add SSH keys to file
  lineinfile:
    line: "{{ item }}"
    dest: "/tmp/auth_keys"
    state: present
  with_url: "{{ key_urls|default([]) }}"

- name: Add SSH keys to file from URLs
  lineinfile:
    line: "{{ item }}"
    dest: "/tmp/auth_keys"
    state: present
  with_items:
    - "{{ keys_ssh|default([]) }}"

- name: Set authorized key
  authorized_key:
    user: "{{ host_username }}"
    state: present
    key: "{{ item }}"
    exclusive: true
  with_file:
    - "/tmp/auth_keys"
