---
- when: docker_configure
  block:
    - name: Write docker default conifg
      template:
        src: daemon.json.j2
        dest: /etc/docker/daemon.json

    - name: Reload docker
      service:
        name: docker
        state: restarted
        enabled: yes
